<?php

/**
 * @file
 * Hooks for the Custom Access Prodact module.
 */

/**
 * Implements hook_theme().
 */
function custom_access_prodact_theme($existing, $type, $theme, $path) {
  return [
    'custom_page' => [
      'variables' => ['data' => NULL],
  // Maps to templates/custom-page.html.twig.
      'template' => 'custom-page',
      'path' => \Drupal::service('extension.path.resolver')->getPath('module', 'custom_access_prodact') . '/templates',
    ],

  ];
}
